[package]
name = "ps-battery"
version = "0.1.0"
edition = "2024"

[dependencies]
hidapi = "2.6.3"
notify-rust = "4.11.7"
tokio = "1.47.1"
windows = { version = "0.62.2", features = [
    "UI_Notifications",
    "Data_Xml_Dom"
] }
