[package]
name = "ps-battery"
version = "0.1.0"
edition = "2024"

[dependencies]
hidapi = "2.6.3"

[dependencies.windows]
version = "0.62"
features = [
    "UI_Notifications",
    "Data_Xml_Dom",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_UI_Shell",
    "Win32_System_Variant",
]
