name: Create Release from Tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps-battery
          path: target/release/ps-battery.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ps-battery
          path: .

      - name: Get version from tag
        id: get_version
        shell: bash
        run: |
          ref="${GITHUB_REF#refs/tags/}"
          version="${ref#v}"
          echo "Detected version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "v${{ steps.get_version.outputs.version }}"
          tag_name: "v${{ steps.get_version.outputs.version }}"
          files: ps-battery.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
