name: Build and Release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build executable
        run: cargo build --release

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/ps-battery.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
