on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: rust
          manifest-file: Cargo.toml
          config-file: .release-please-config.json
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release

      - name: Install latest Cosign
        shell: pwsh
        run: |
          curl -L https://github.com/sigstore/cosign/releases/latest/download/cosign-windows-amd64.exe -o cosign.exe
          mkdir -p $env:USERPROFILE\bin
          move cosign.exe $env:USERPROFILE\bin\cosign.exe
          echo "$env:USERPROFILE\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Sign binary with Sigstore
        shell: pwsh
        run: |
          cosign sign-blob `
            target/release/ps-battery.exe `
            --yes `
            --bundle target/release/ps-battery.exe.bundle

      - name: Upload .exe and bundle to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: |
            target/release/ps-battery.exe
            target/release/ps-battery.exe.bundle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
