name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release

      - name: Package binary (ZIP)
        run: Compress-Archive -Path target/release/ps-battery.exe -DestinationPath ps-battery.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps-battery
          path: ps-battery.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ps-battery
          path: .

      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ steps.version.outputs.version }}"
          tag_name: "${{ steps.version.outputs.version }}"
          files: ps-battery.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
