name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Rename binary with version
        shell: bash
        run: |
          version=$(awk -F '"' '/^version =/ && in_package {print $2; exit} /^\[package\]/ {in_package=1}' Cargo.toml)
          echo "Detected version: $version"
          mkdir dist
          cp target/release/ps-battery.exe "dist/ps-battery-v${version}.exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps-battery
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ps-battery
          path: ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
