name: Version and Tag
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: rust
          manifest-file: Cargo.toml
          config-file: .release-please-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
